{% set version = "2022.3.0" %}
{% set tag = "ufl_legacy-" + version %}

package:
  name: fenics-ufl-legacy
  version: {{ version }}

source:
  url: https://github.com/FEniCS/ufl/archive/refs/tags/ufl_legacy-{{ version }}.tar.gz
  sha256: 613b83ad0e7867beeaf7e5598cd3f3023a3c433f1c319bd8d931e2b7012ee27a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools
    - numpy
test:
  imports:
    - ufl_legacy
    - ufl_legacy.utils
    - ufl_legacy.finiteelement
    - ufl_legacy.core
    - ufl_legacy.corealg
    - ufl_legacy.algorithms

about:
  home: https://www.fenicsproject.org
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Unified Form Language (Legacy)

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (https://fenicsproject.org). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: https://fenics.readthedocs.io
  dev_url: https://github.com/fenics/ufl

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
    - jan-janssen
